### ISSUE TITLE
Layout problem on mobile device

### ISSUE THREAD

**Issue by moravcik** [dbtek/angular-hamburger-toggle#4]
After opening the hamburger menu on mobile device (LG G4) the entire page is somehow zoomed out and the center area is too narrow, see screenshot

![screenshot_2015-08-13-20-04-32](https://cloud.githubusercontent.com/assets/1102311/9258049/80f51520-41f9-11e5-851f-94ab30320ca5.png)

**Comment by dbtek** [comment]
Hi @moravcik,

Thanks for reporting. I look into that when I got the time. 

However, this is about demo page only, not being responsive. Hamburger toggle is only the toggle button.

TLDR: You still can use the component.
