### ISSUE TITLE
How to make the arrow point to the right

### ISSUE THREAD

**Issue by alexcoroza** [dbtek/angular-hamburger-toggle#6]
By default, the arrow faces to the left, but I want it to face right since my side nav is in the right. Theres nothing in documentation discusses about this

**Comment by dbtek** [comment]
Morphing icon is based on [Material Design Hamburger](https://github.com/chrisdwheatley/material-design-hamburger) you can try things on [this pen](http://codepen.io/chrisdwheatley/pen/cFtzb).

Sorry for the delay.
